apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-lab-ingress
  namespace: 2048-game   # ✅ Added namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance 
    alb.ingress.kubernetes.io/healthcheck-path: /health
spec:
  rules:
    - host: eks-lab.example.soumitripathy.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eks-lab-service
                port:
                  number: 8080
