apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eks-lab-ingress
  namespace: 2048-game   # ✅ Added namespace
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance 
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-south-1:279604517008:certificate/72d8c7a8-4478-4334-8233-da75f13294bc
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
spec:
  rules:
    - host: eks-lab.example.soumitripathy.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eks-lab-service
                port:
                  number: 8080
