apiVersion: v1
kind: Service
metadata:
  name: eks-lab-service
  namespace: 2048-game   # ✅ Added namespace
spec:
  selector:
    app: eks-lab-project
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
